var SqrGeoRng = require('./sqr_geo_rng');
var mongoose = require('mongoose');

/** Class representing a database server*/
module.exports = class ServerInfo {
    /**
     * Create a ServerInfo
     * @constructor
     * @param {string} baseAddr - The base address of the server
     * @param {string} backupAddr - The address the server backs up its data 
     *  too
     * @param {SqrGeoRng} writeRng - The geographic range of posts that
     *  should be stored at this server
     * @param {SqrGeoRng} readRng - The geographic range of posts that can
     *  possibly be read from this server, must always fully encompass the write 
     *  range
     * @param {mongoose.Schema.Types.ObjectId} _id - The database ID of the 
     *  server, autogenerated if unspecified
     */
    constructor(baseAddr, backupAddr, writeRng, readRng, _id) {
        this.baseAddr = baseAddr;
        this.backupAddr = backupAddr;
        this.writeRng = (writeRng ? writeRng : new SqrGeoRng());
        this.readRng = (readRng ? readRng : new SqrGeoRng());
        if (_id) {
            this._id = _id;
        } else {
            this._id = mongoose.Types.ObjectId();
        }
    }

    /**
     * Convert a javascript object with the same fields as a ServerInfo into a 
     * ServerInfo object
     * @param {Object} obj
     * @param {number} obj.baseAddr
     * @param {number} obj.backupAddr
     * @param {SqrGeoRng} obj.writeRng
     * @param {SqrGeoRng} obj.readRng
     * @param {string} obj._id
     */
    static convertObjToClass(obj) {
        let baseAddr = obj.baseAddr;
        let backupAddr = obj.backupAddr;
        let writeRng = SqrGeoRng.convertObjToClass(obj.writeRng);
        let readRng = SqrGeoRng.convertObjToClass(obj.readRng);
        let _id = obj._id;
        return new ServerInfo(baseAddr, backupAddr, writeRng, readRng, _id);
    }

    /**
     * Get the structure of this class in the format required for a Mongoose 
     * Schema
     * @returns {Object} - The class structure
     */
    static getStructure() {
        return {
            baseAddr: {
                type: String,
                required: true,
            },
            backupAddr: {
                type: String,
                required: true,
            },
            writeRng: {
                type: SqrGeoRng.getStructure(),
                required: true,
            },
            readRng: {
                type: SqrGeoRng.getStructure(),
                required: true,
            },
            _id: {
                type: mongoose.Schema.Types.ObjectId,
                required: true
            }
        };
    }
}